# Generated by Django 5.2.6 on 2025-09-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('input_placeholder_name', models.CharField(max_length=30)),
                ('input_placeholder_email', models.CharField(max_length=30)),
                ('input_placeholder_phone', models.CharField(max_length=30)),
                ('btn_text', models.CharField(max_length=30)),
                ('priacy_policy_text', models.CharField(max_length=100)),
                ('priacy_policy_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('map_image', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address_icon', models.FileField(upload_to='contact-page/')),
                ('phone_icon', models.FileField(upload_to='contact-page/')),
                ('email_icon', models.FileField(upload_to='contact-page/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.FileField(upload_to='contact-page/')),
            ],
        ),
    ]
