# Generated by Django 5.2.6 on 2025-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=100)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('image', models.FileField(upload_to='about-us/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='about-us/')),
            ],
            options={
                'verbose_name_plural': 'About us',
            },
        ),
    ]
