# Generated by Django 5.2.6 on 2025-09-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='header.navbar')),
            ],
        ),
    ]
