# Generated by Django 5.2.6 on 2025-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_icon', models.ImageField(upload_to='header_icons/')),
                ('heart_icon', models.ImageField(upload_to='header_icons/')),
                ('cart_icon', models.ImageField(upload_to='header_icons/')),
                ('language_arrow_icon', models.ImageField(upload_to='header_icons/')),
            ],
        ),
    ]
