# Generated by Django 5.2.6 on 2025-09-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_headericon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headericon',
            name='cart_icon',
            field=models.FileField(upload_to='header_icons/'),
        ),
        migrations.AlterField(
            model_name='headericon',
            name='heart_icon',
            field=models.FileField(upload_to='header_icons/'),
        ),
        migrations.AlterField(
            model_name='headericon',
            name='language_arrow_icon',
            field=models.FileField(upload_to='header_icons/'),
        ),
        migrations.AlterField(
            model_name='headericon',
            name='search_icon',
            field=models.FileField(upload_to='header_icons/'),
        ),
    ]
