# Generated by Django 5.2.6 on 2025-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0003_alter_headericon_cart_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('label', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='header_icons/')),
            ],
        ),
    ]
