# Generated by Django 5.2.6 on 2025-09-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
