# Generated by Django 5.2.6 on 2025-09-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_delete_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('label', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='header_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
