# Generated by Django 5.2.6 on 2025-09-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0006_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeaderIcon',
        ),
        migrations.RemoveField(
            model_name='submenu',
            name='navbar',
        ),
        migrations.DeleteModel(
            name='Navbar',
        ),
        migrations.DeleteModel(
            name='Submenu',
        ),
    ]
