# Generated by Django 5.2.6 on 2025-09-11 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_delete_headericon_remove_submenu_navbar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_icon', models.FileField(upload_to='header_icons/')),
                ('heart_icon', models.FileField(upload_to='header_icons/')),
                ('cart_icon', models.FileField(upload_to='header_icons/')),
                ('language_arrow_icon', models.FileField(upload_to='header_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='header.navbar')),
            ],
        ),
    ]
