# Generated by Django 5.2.6 on 2025-09-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0008_headericon_navbar_submenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='navbar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='header.navbar'),
        ),
    ]
