# Generated by Django 5.2.6 on 2025-09-11 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0009_alter_submenu_navbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='navbar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='header.navbar'),
        ),
    ]
