# Generated by Django 5.2.6 on 2025-09-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0010_alter_submenu_navbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headericon',
            options={'verbose_name': 'icon', 'verbose_name_plural': 'Icons'},
        ),
    ]
