# Generated by Django 5.2.6 on 2025-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0011_alter_headericon_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketHeartViewLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedBasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('remove_button_icon', models.FileField(upload_to='header_icons/')),
                ('remove_button_text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavedHeartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=100)),
                ('add_button_icon', models.FileField(upload_to='header_icons/')),
                ('add_button_text', models.CharField(max_length=100)),
                ('remove_button_icon', models.FileField(upload_to='header_icons/')),
                ('remove_button_text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
