# Generated by Django 5.2.6 on 2025-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0012_basketheartviewlink_savedbasketitem_savedheartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedbasketitem',
            name='remove_button_icon',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='savedheartitem',
            name='add_button_icon',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='savedheartitem',
            name='remove_button_icon',
            field=models.CharField(max_length=5),
        ),
    ]
