# Generated by Django 5.2.6 on 2025-09-11 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('descr', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='global/category/')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('product_number', models.CharField(max_length=255, unique=True)),
                ('price', models.FloatField()),
                ('heart_icon', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('group_code', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.JSONField()),
                ('btn_text', models.JSONField()),
                ('descr', models.JSONField()),
                ('product_material', models.JSONField()),
                ('about_delivery', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='global/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='global/items/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='global_data.item')),
            ],
        ),
    ]
