# Generated by Django 5.2.6 on 2025-09-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('main', models.CharField(max_length=100)),
                ('catalog', models.CharField(max_length=100)),
                ('filter_by', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('sort_by', models.CharField(max_length=100)),
                ('from_field', models.CharField(max_length=100)),
                ('to_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InfoAboutDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('texts', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemFaqHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('image', models.FileField(upload_to='global/items-header/')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('descr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('item', models.CharField(max_length=30)),
                ('catalog', models.CharField(max_length=30)),
                ('cribs', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPageField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('size_text_field', models.CharField(max_length=255)),
                ('size_text_field_2', models.CharField(max_length=255)),
                ('descr_text_field', models.CharField(max_length=255)),
                ('product_number_text_field', models.CharField(max_length=255)),
                ('material_text_field', models.CharField(max_length=255)),
                ('about_delivery_text_field', models.CharField(max_length=255)),
                ('not_available_text_field', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LikedProductHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
    ]
