# Generated by Django 5.2.6 on 2025-09-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_data', '0002_categories_link_infoaboutdelivery_itemfaq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
