# Generated by Django 5.2.6 on 2025-09-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_data', '0003_item_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfaq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='itemfaq',
            name='question',
            field=models.TextField(),
        ),
    ]
