# Generated by Django 5.2.6 on 2025-10-31 15:55

import global_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_data', '0004_alter_itemfaq_answer_alter_itemfaq_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAboutDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_delivery', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='about_delivery',
        ),
        migrations.AddField(
            model_name='item',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='btn_text',
            field=models.JSONField(default=global_data.models.default_btn_text),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_number',
            field=models.CharField(default=global_data.models.generate_product_number, max_length=255, unique=True),
        ),
    ]
