# Generated by Django 5.2.6 on 2025-09-14 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopingbagpage',
            options={'verbose_name': 'Shopping bag page data', 'verbose_name_plural': 'Shopping bag page data'},
        ),
    ]
