# Generated by Django 5.2.6 on 2025-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('btn_text', models.CharField(max_length=50)),
                ('btn_url', models.CharField(max_length=50)),
                ('image_1', models.FileField(upload_to='home-page/about')),
                ('image_2', models.FileField(upload_to='home-page/about')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=100)),
                ('map_image', models.FileField(upload_to='home-page/contact')),
                ('map_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NewArrivalsHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='home-page/partners')),
            ],
        ),
        migrations.CreateModel(
            name='PartnersHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PopularItemHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=255)),
                ('btn_text', models.CharField(max_length=20)),
                ('btn_url', models.CharField(max_length=20)),
                ('background_image', models.FileField(upload_to='home-page/')),
                ('image', models.FileField(upload_to='home-page/slider/')),
            ],
        ),
        migrations.CreateModel(
            name='SliderIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_icon', models.FileField(upload_to='home-page/slider')),
                ('left_arrow_icon', models.FileField(upload_to='home-page/slider')),
                ('right_arrow_icon', models.FileField(upload_to='home-page/slider')),
            ],
        ),
    ]
