# Generated by Django 5.2.6 on 2025-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact us'},
        ),
    ]
