# Generated by Django 5.2.6 on 2025-09-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_data', '0002_categories_link_infoaboutdelivery_itemfaq_and_more'),
        ('home_page', '0004_alter_aboutus_options_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_items', to='global_data.item')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
