# Generated by Django 5.2.6 on 2025-09-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_popularitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularItem',
        ),
    ]
