# Generated by Django 5.2.6 on 2025-09-11 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterInfo',
        ),
        migrations.DeleteModel(
            name='FooterSocialLink',
        ),
    ]
