# Generated by Django 5.2.6 on 2025-09-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'Footer Info', 'verbose_name_plural': 'Infos'},
        ),
        migrations.AlterModelOptions(
            name='footerprivacypolicy',
            options={'verbose_name': 'Footer Privacy policy', 'verbose_name_plural': 'Privacy policy'},
        ),
        migrations.AlterModelOptions(
            name='footersociallink',
            options={'verbose_name': 'Footer Social link', 'verbose_name_plural': 'Social links'},
        ),
    ]
